Repository chas-academy/u08-business-idea-team1-bokmalarna, pull requests merged in 2022-06, with the labels that each got.

#127 Navbar fix
  frontend/src/App.js
  frontend/src/components/login/Login.js
Labels: front, pr

#129 Search form
  backend/routes/book.js
  backend/routes/user.js
  backend/server.js
  frontend/src/App.js
  frontend/src/components/search/Search.js
Labels: pr

#131 Development
  .gitignore
  backend/routes/book.js
  backend/routes/user.js
  backend/server.js
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/bookpage/Bookpage.js
  frontend/src/components/edit/Edit.js
  frontend/src/components/edit/Editpassword.js
  frontend/src/components/footer/Footer.js
  frontend/src/components/login/Login.js
  frontend/src/components/search/Search.js
  frontend/src/index.js
  package-lock.json
  package.json
Labels: front, backend, pr

#147 Get user books
  backend/.gitignore
  frontend/src/components/dashboard/Dashboard.js
Labels: pr

#148 Fix colours in app
  frontend/src/App.js
  frontend/src/index.css
Labels: pr

#150 Fix login style
  frontend/src/components/login/Login.js
Labels: pr

#151 Tests
  frontend/cypress.config.js
  frontend/cypress/e2e/login.cy.js
  frontend/cypress/e2e/register.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.js
  readme.md
Labels: pr

#153 Get all users borrowed books
  backend/routes/book.js
  frontend/src/components/dashboard/Dashboard.js
  readme.md
Labels: pr

#155 layout problem fix in mobile view and desktop
  frontend/src/components/Home/Home.js
  frontend/src/index.css
Labels: pr

#156 Colorfix
  frontend/public/favicon.ico
  frontend/src/App.js
  frontend/src/components/addbook/Addbook.js
  frontend/src/components/bookpage/Bookpage.js
  frontend/src/components/footer/Footer.js
  frontend/src/components/nav/nav.js
  frontend/src/index.css
Labels: pr

#157 add copyright to footer
  frontend/public/copyright.png
  frontend/src/components/footer/Footer.js
  frontend/src/index.css
Labels: pr

#161 Search form
  backend/routes/book.js
  backend/routes/user.js
  frontend/cypress/e2e/search.cy.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/bookpage/Bookpage.js
  frontend/src/components/login/Login.js
  frontend/src/components/search/Search.js
  readme.md
Labels: pr

#163 Search form
  backend/routes/book.js
  frontend/src/components/search/Search.js
Labels: pr

#164 update readme
  readme.md
Labels: pr

#167 Merge dev to main to trigger deploy build
  backend/.gitignore
  backend/routes/book.js
  backend/routes/user.js
  frontend/cypress.config.js
  frontend/cypress/e2e/login.cy.js
  frontend/cypress/e2e/register.cy.js
  frontend/cypress/e2e/search.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/copyright.png
  frontend/public/favicon.ico
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/Home/Home.js
  frontend/src/components/addbook/Addbook.js
  frontend/src/components/bookpage/Bookpage.js
  frontend/src/components/dashboard/Dashboard.js
  frontend/src/components/footer/Footer.js
  frontend/src/components/login/Login.js
  frontend/src/components/nav/nav.js
  frontend/src/components/registration/Registration.js
  frontend/src/components/search/Search.js
  frontend/src/index.css
  readme.md
Labels: pr

#178 121 fix edit user settings without login logout
  backend/routes/user.js
  frontend/src/components/edit/Edit.js
Labels: pr

#189 Fix register component
  frontend/src/components/Home/Home.js
  frontend/src/components/registration/Registration.js
Labels: pr

#198 Fix dashboard
  frontend/src/components/dashboard/Dashboard.js
Labels: pr

#200 176 move editpassword into edit
  frontend/src/App.js
  frontend/src/components/edit/Edit.js
  frontend/src/components/edit/Editpassword.js
  frontend/src/components/edit/edit.css
Labels: front, pr

#201 Change names
  frontend/src/App.js
  frontend/src/components/Home/Home.js
  frontend/src/components/login/Login.js
  frontend/src/components/registration/Registration.js
Labels: pr

#204 Trigger deploy 2.0
  backend/package-lock.json
Labels: pr

#214 Bookpage fixes
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/bookpage/Bookpage.js
Labels: pr

#215 Delete user fe
  backend/npm-debug.log
  frontend/src/App.js
  frontend/src/components/dashboard/Dashboard.js
  frontend/src/components/edit/Edit.js
  npm-debug.log
Labels: task, front, backend, pr

#219 make single book api send users city
  backend/routes/book.js
Labels: pr

#221 fix owners city even if logged out
  backend/socket/package-lock.json
  frontend/src/components/bookpage/Bookpage.js
Labels: bug, pr

#223 Message
  backend/socket/index.js
  frontend/src/components/messenger/Messenger.js
Labels: pr

#228 179 reset password
  backend/routes/user.js
  frontend/src/components/edit/Edit.js
Labels: front, backend, pr

#229 Message
  frontend/src/App.css
  frontend/src/components/messenger/Message.js
  frontend/src/components/messenger/Messenger.js
Labels: pr

#230 Fix browse page
  frontend/src/components/footer/Footer.js
  frontend/src/components/search/Search.js
  frontend/src/index.css
Labels: pr

#233 Fix addbook
  backend/models/book.js
  frontend/src/components/addbook/Addbook.js
Labels: front, backend, pr

#234 231 add alert message on password reset
  backend/routes/user.js
  frontend/src/components/edit/Edit.js
  frontend/src/components/edit/edit.css
Labels: front, backend, pr

#235 Message
  backend/routes/book.js
  frontend/src/components/dashboard/Dashboard.js
  frontend/src/index.css
Labels: pr

#238 Fix terminal warnings
  backend/routes/book.js
  backend/routes/user.js
  backend/socket/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/addbook/Addbook.js
  frontend/src/components/bookpage/Bookpage.js
  frontend/src/components/dashboard/Dashboard.js
  frontend/src/components/edit/Edit.js
  frontend/src/components/edit/Editbook.js
  frontend/src/components/edit/edit.css
  frontend/src/components/footer/Footer.js
  frontend/src/components/login/Login.js
  frontend/src/components/registration/Registration.js
  frontend/src/components/search/Search.js
  frontend/src/index.js
Labels: bug, front, backend, pr

#241 Message
  frontend/src/App.css
  frontend/src/components/dashboard/Dashboard.js
  frontend/src/components/messenger/Messenger.js
Labels: pr
